### ISSUE TITLE
How to print in black and white with a ".dat" file

### ISSUE THREAD

**Issue by urtzi2** [FOGProject/fog-client#139] opened 2022-03-15 09:37 UTC
Hi everyone,
I want to set up a printer with a .dat file on the fog server. The first thing I have done is to go to the fog documentation and I have found a command to export a config file which is the following: [documentation](https://docs.fogproject.org/en/latest/management/printer-management.html)

- RUNDLL32 PRINTUI.DLL,PrintUIEntry /Ss /n"Printer Name" /a "C:\Path\To\Save\ConfigFile.dat m f g p

I have tried the command in MS2 with a printer that I had in black and white, I have made the config file of that, the question is that this command does not do what I want that is to configure the printer in black and white, but if I change the letters of the parameter /Ss and /Sr the letter "g" of the command by the "u" the configuration is saved in black and white. 

-`RUNDLL32 PRINTUI.DLL,PrintUIEntry /Sr /n "PrinterBW" /a "C:\ConfigFile2.dat" m f u p`
-`RUNDLL32 PRINTUI.DLL,PrintUIEntry /Ss /n "PrinterBW" /a "C:\ConfigFile2.dat" m u `

Now what I want to do is the same but in the fog server but when I put the .dat file in the configuration of the printers it does the same as the command with the "g" and I don't know how to make it do the same as the "u", does anyone know?
thanks in advance.

**Comment by Sebastian-Roth** [comment] 2022-11-26 15:57
@iPaulis @urtzi2 Sorry for the long delay. I finally found some time to dig into this topic again.

Now that I have read through this again and again I get the impression that this might be based on a simple misunderstanding. I might be wrong but let me explain what I mean. See this picture were printer settings are shown:

![print_settings](https://user-images.githubusercontent.com/16324704/204097297-7f35bb7f-ebab-460b-8e92-f680d5b0fbd3.jpg)

The first one called "Preferences" (General tab) is what you would call user mode settings. The second circle marks the "Printer Defaults" (Advanced tab) corresponding to what is called global mode in the [PrintUI documentation](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/rundll32-printui). Looks like you can't mix the settings files. When exported as user mode it can't be imported as global and vice versa.

Is there a good reason why you want to adjust user mode settings instead of the global printer settings?

Be aware of a recent topic in the forums as well: https://forums.fogproject.org/topic/16252/printer-configuration-file-not-applied

**Comment by iPaulis** [comment] 2022-12-14 20:11
Hi, what we were trying to achieve was to save a config file in windows and then load it into fog to be able to automatically apply a default black and white setting when fog sets up a printer in the client computer.

As explained above, I followed the instructions in [fog's documentation](https://docs.fogproject.org/en/latest/management/printer-management.html), so I exported a .dat file from a printer that I had set to black and white, then created a new printer in fog pointing to that .dat file. Then I saw that the new printer was added into the client computer, but it was not in black and white. 
To be completely sure that the .dat file was being applied, I created the printer locally in Windows using the exact same command that fogclient uses. The result was that it created the printer, but did not apply the black and white setting. So I got the same result locally as fog, that made me think there was something wrong in that command. 

> Steps to reproduce locally:
> 1. Create a printer setting, set it to black and white
> 2. Open MS-DOS and type the command as show in the Fog documentation to export a .dat file:
> `RUNDLL32 PRINTUI.DLL,PrintUIEntry /Ss /n "PrinterName" /a "C:\ConfigFile.dat" m f g p`
> 3. Set the printer back to colour.
> 4. Type in MS-DOS the command to import:
> `RUNDLL32 PRINTUI.DLL,PrintUIEntry /Sr /n "PrinterName" /a "C:\ConfigFile.dat" m f g p`
> 5. Check if the black and white setting has applied --> it does not apply black and white setting
> 
> Repeating the steps with only one change as suggested, instead of using `m f g p` parameters, by using `m f u p` parameters, fixes the problem, and anyone should be able reproduce it and see it does apply black and white settings.

I don't want to mix the settings files, I just want the settings file to apply black and white by deafult and work as expected. 
That is why I checked locally in 2-3 different computers that exporting and importing a .dat file in global mode (g parameter) the black and white setting was not being applied, while exporting and importing a .dat file in user mode (u parameter) it did work. I confirmed this several times to be sure and the results were consistent.

So the suggestion was to fix the problem just by changing the parameter that fogclient uses to import the .dat file from `g` to `u`, and to update the documentation accordingly. 

The only reason why I wanted to adjust user mode settings is because it works, it applies black and white and fixes this issue.

I also read the forum post, and if there is another way to make this work, that's perfect, I would just like to be able to create a printer that is set up in black and white as default. If a new version is released that includes a fix I'll happily test and confirm it.

Thank you for your help.

**Comment by Sebastian-Roth** [comment] 2022-12-16 01:14
@iPaulis said:
> The only reason why I wanted to adjust user mode settings is because it works, it applies black and white and fixes this issue.

I fully understand this. I just can't replicate the issue as described on my test system and that's why I did post the screenshot to show the difference of user/global mode settings.

So if you say "black and white" surely doesn't work in global mode in your case I am pretty sure the printer driver has a bug. But I won't start arguing about this. We can't fix the printer driver and discussing the bug is useless. Therefore I will try to add some more logic to the fog-client code:

* Check to see if parameter `printer.ConfigFile` is a file and readable (e.g. `C:\ConfigFile.dat`):
  1. If that's the case, then load using `... m f g p` first and then again with `... m f u p` - I hope that loading twice using global and user mode one after the other is not causing trouble.
  2. Instead if `printer.ConfigFile` is not pointing to an existing file then we assume it includes the loading parameters as well, e.g. `C:\ConfigFile.dat m f u p` - in that case try splitting up the variable until a valid file is found and can be loaded using the load parameters given.

**Comment by iPaulis** [comment] 2022-12-16 02:27
It has been many months and I would have liked to retest and confirm the issue, but unfortunately I'm not at the location of the printers/computers and won't be back shortly. 
However, as soon as I can I will reproduce and try everything again from scratch in new computers with a couple of printers to definitely learn how it works, and if there is a new version of fog-client released by then I will try that too. 
I would love to make this work for the more than 300 computers and 10 printers that I manage.

Thank you again for your help, I hope everything goes well.

**Comment by Sebastian-Roth** [comment] 2022-12-25 07:31
@iPaulis @urtzi2 We have a new DLL ready for testing, thanks to @Iri5s.

Download the new [Modules.dll from github](https://github.com/FOGProject/fog-client/releases/download/0.12.2/Modules_custom_PrintUI.dll) on your test machine. Stop the `FOGService` (Windows services management). Rename the original `C:\Program Files (x86)\FOG\Modules.dll` (e.g. to `Modules_orig.dll`) and put the newly downloaded one in place. Then start `FOGService` again.

With that DLL it will try to set the printer config .dat file in user mode as well as global mode. See if that works out of the box without changing you settings. If it doesn't work then you can change the **Printer INF File** setting and add `m f u p` at the end (after the filename separated by a space).

Please report back.

**Comment by iPaulis** [comment] 2022-12-25 23:28
Thank you very much for the fix @Iri5s and @Sebastian-Roth.

I won't be back at the office for a while, so I can't test this right away, but I will sure do it eventually and report back.

**Comment by Sebastian-Roth** [comment] 2023-01-08 11:55
Closing as fixed - pretty sure this is working as intended.

@iPaulis Feel free to update this issue report whenever you get to test this.

**Closed by Sebastian-Roth** 2023-01-08 11:55 UTC
Labels: enhancement, needs testing
